# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analize.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 421, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.analize = QtWidgets.QPushButton(self.frame)
        self.analize.setGeometry(QtCore.QRect(320, 20, 75, 101))
        self.analize.setObjectName("analize")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 291, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 16))
        self.label.setObjectName("label")
        self.data = QtWidgets.QComboBox(self.frame_2)
        self.data.setGeometry(QtCore.QRect(10, 30, 261, 20))
        self.data.setObjectName("data")
        self.data.addItem("")
        self.data.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.label_2.setObjectName("label_2")
        self.type = QtWidgets.QComboBox(self.frame_2)
        self.type.setGeometry(QtCore.QRect(10, 80, 261, 20))
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.show = QtWidgets.QListWidget(self.frame)
        self.show.setGeometry(QtCore.QRect(10, 130, 391, 171))
        self.show.setObjectName("show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analize.setText(_translate("MainWindow", "Analizar"))
        self.label.setText(_translate("MainWindow", "Seleccion de analisis"))
        self.data.setItemText(0, _translate("MainWindow", "Datos"))
        self.data.setItemText(1, _translate("MainWindow", "Tiempo real"))
        self.label_2.setText(_translate("MainWindow", "Seleccion de falla"))
        self.type.setItemText(0, _translate("MainWindow", "Barra Rotas"))
        self.type.setItemText(1, _translate("MainWindow", "Cortocircuito"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
